library(XML)

con=url("https://highwaypolice.maharashtra.gov.in/en/reports/")
htmlCode = readLines(con)
close(con)
recentyears <- readHTMLTable(htmlCode, which =1)
head(recentyears)
class(recentyears)
write.csv(recentyears, "D:\\Data Science\\R\\recentyears.csv")
recentyears <- read.csv("D:\\Data Science\\R\\recentyears.csv")
head(recentyears)
summary(recentyears)
hist(recentyears)
is.na(recentyears)
hist(recentyears$Years)
plot(recentyears$Years, recentyears$Total.Accidents)
year2016 <- readHTMLTable(htmlCode, which=2)
year2017 <- readHTMLTable(htmlCode, which=3)
year2018 <- readHTMLTable(htmlCode, which=4)
year2019 <- readHTMLTable(htmlCode, which=5)
write.csv(year2016, "D:\\Data Science\\R\\years2016.csv")
write.csv(year2017, "D:\\Data Science\\R\\years2017.csv")
write.csv(year2018, "D:\\Data Science\\R\\years2018.csv")
write.csv(year2019, "D:\\Data Science\\R\\years2019.csv")
year2016 <- read.csv("D:\\Data Science\\R\\years2016.csv")
year2017 <- read.csv("D:\\Data Science\\R\\years2017.csv")
year2018 <- read.csv("D:\\Data Science\\R\\years2018.csv")
year2019 <- read.csv("D:\\Data Science\\R\\years2019.csv")
install.packages("ggplot2")
library(ggplot2)
qplot(Total.Accidents, year2016$total.accident, data = recentyears, geom="smooth")
qplot(Total.Accidents, Years, data = recentyears, geom="smooth")
